-- CreateTable
CREATE TABLE "USER" (
    "USR_ID" SERIAL NOT NULL,
    "USR_FirstName" TEXT NOT NULL,
    "USR_LastName" TEXT NOT NULL,
    "USR_Email" TEXT NOT NULL,
    "USR_PasswordHash" TEXT NOT NULL,
    "USR_Role" TEXT NOT NULL,
    "USR_Status" TEXT NOT NULL,
    "USR_CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USR_UpdatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("USR_ID")
);

-- CreateTable
CREATE TABLE "SYSTEM_LOG" (
    "LOG_ID" SERIAL NOT NULL,
    "LOG_Level" TEXT NOT NULL,
    "LOG_EventType" TEXT NOT NULL,
    "LOG_Message" TEXT NOT NULL,
    "LOG_CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USER_USR_ID" INTEGER NOT NULL,

    CONSTRAINT "SYSTEM_LOG_pkey" PRIMARY KEY ("LOG_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_USR_Email_key" ON "USER"("USR_Email");

-- AddForeignKey
ALTER TABLE "SYSTEM_LOG" ADD CONSTRAINT "SYSTEM_LOG_USER_USR_ID_fkey" FOREIGN KEY ("USER_USR_ID") REFERENCES "USER"("USR_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
