-- CreateTable
CREATE TABLE "DUPLICATE_GROUP" (
    "DPG_ID" SERIAL NOT NULL,
    "DPG_Type" TEXT NOT NULL,
    "DPG_Fingerprint" TEXT NOT NULL,
    "DPG_CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DUPLICATE_GROUP_pkey" PRIMARY KEY ("DPG_ID")
);

-- CreateTable
CREATE TABLE "SCAN_JOB" (
    "SCN_ID" SERIAL NOT NULL,
    "SCN_Status" TEXT NOT NULL,
    "SCN_StartedAt" TIMESTAMP(3),
    "SCN_CompletedAt" TIMESTAMP(3),
    "SCN_TotalURLs" INTEGER NOT NULL,
    "SCN_ProcessedURLs" INTEGER NOT NULL DEFAULT 0,
    "SCN_FailedURLs" INTEGER NOT NULL DEFAULT 0,
    "URL_BATCH_BAT_ID" INTEGER NOT NULL,

    CONSTRAINT "SCAN_JOB_pkey" PRIMARY KEY ("SCN_ID")
);

-- CreateTable
CREATE TABLE "SCAN_RESULT" (
    "RES_ID" SERIAL NOT NULL,
    "RES_HTTPStatus" INTEGER,
    "RES_StatusLabel" TEXT NOT NULL,
    "RES_FinalURL" TEXT,
    "RES_RedirectCount" INTEGER NOT NULL DEFAULT 0,
    "RES_ResponseTimeMs" INTEGER,
    "RES_ErrorType" TEXT,
    "RES_ManualReviewRequired" BOOLEAN NOT NULL DEFAULT false,
    "RES_CheckedAt" TIMESTAMP(3),
    "SCAN_JOB_SCN_ID" INTEGER NOT NULL,
    "URL_URL_ID" INTEGER NOT NULL,

    CONSTRAINT "SCAN_RESULT_pkey" PRIMARY KEY ("RES_ID")
);

-- CreateTable
CREATE TABLE "PAGE_ANALYSIS" (
    "PGA_ID" SERIAL NOT NULL,
    "PGA_Title" TEXT,
    "PGA_MetaDescription" TEXT,
    "PGA_Headings" TEXT,
    "PGA_InternalLinkCount" INTEGER NOT NULL,
    "PGA_ExternalLinkCount" INTEGER NOT NULL,
    "PGA_FormCount" INTEGER NOT NULL,
    "PGA_HasCommentSection" BOOLEAN NOT NULL,
    "PGA_HasUserInput" BOOLEAN NOT NULL,
    "PGA_ContentPreview" TEXT,
    "PGA_AnalyzedAt" TIMESTAMP(3) NOT NULL,
    "SCAN_RESULT_RES_ID" INTEGER NOT NULL,

    CONSTRAINT "PAGE_ANALYSIS_pkey" PRIMARY KEY ("PGA_ID")
);

-- CreateTable
CREATE TABLE "AI_EVALUATION" (
    "AIE_ID" SERIAL NOT NULL,
    "AIE_RelevanceLabel" TEXT NOT NULL,
    "AIE_RelevanceScore" DECIMAL(5,2),
    "AIE_QualityLabel" TEXT,
    "AIE_SpamLike" BOOLEAN NOT NULL,
    "AIE_Explanation" TEXT,
    "AIE_RecommendedAction" TEXT,
    "AIE_EvaluatedAt" TIMESTAMP(3) NOT NULL,
    "SCAN_RESULT_RES_ID" INTEGER NOT NULL,

    CONSTRAINT "AI_EVALUATION_pkey" PRIMARY KEY ("AIE_ID")
);

-- CreateTable
CREATE TABLE "CACHE_RECORD" (
    "CAC_ID" SERIAL NOT NULL,
    "CAC_URLFingerprint" TEXT NOT NULL,
    "CAC_ContentFingerprint" TEXT,
    "CAC_CachedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CAC_ExpiresAt" TIMESTAMP(3) NOT NULL,
    "CAC_IsValid" BOOLEAN NOT NULL DEFAULT true,
    "SCAN_RESULT_RES_ID" INTEGER NOT NULL,

    CONSTRAINT "CACHE_RECORD_pkey" PRIMARY KEY ("CAC_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "PAGE_ANALYSIS_SCAN_RESULT_RES_ID_key" ON "PAGE_ANALYSIS"("SCAN_RESULT_RES_ID");

-- CreateIndex
CREATE UNIQUE INDEX "AI_EVALUATION_SCAN_RESULT_RES_ID_key" ON "AI_EVALUATION"("SCAN_RESULT_RES_ID");

-- AddForeignKey
ALTER TABLE "URL" ADD CONSTRAINT "URL_DUPLICATE_GROUP_DPG_ID_fkey" FOREIGN KEY ("DUPLICATE_GROUP_DPG_ID") REFERENCES "DUPLICATE_GROUP"("DPG_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCAN_JOB" ADD CONSTRAINT "SCAN_JOB_URL_BATCH_BAT_ID_fkey" FOREIGN KEY ("URL_BATCH_BAT_ID") REFERENCES "URL_BATCH"("BAT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCAN_RESULT" ADD CONSTRAINT "SCAN_RESULT_SCAN_JOB_SCN_ID_fkey" FOREIGN KEY ("SCAN_JOB_SCN_ID") REFERENCES "SCAN_JOB"("SCN_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCAN_RESULT" ADD CONSTRAINT "SCAN_RESULT_URL_URL_ID_fkey" FOREIGN KEY ("URL_URL_ID") REFERENCES "URL"("URL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PAGE_ANALYSIS" ADD CONSTRAINT "PAGE_ANALYSIS_SCAN_RESULT_RES_ID_fkey" FOREIGN KEY ("SCAN_RESULT_RES_ID") REFERENCES "SCAN_RESULT"("RES_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AI_EVALUATION" ADD CONSTRAINT "AI_EVALUATION_SCAN_RESULT_RES_ID_fkey" FOREIGN KEY ("SCAN_RESULT_RES_ID") REFERENCES "SCAN_RESULT"("RES_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CACHE_RECORD" ADD CONSTRAINT "CACHE_RECORD_SCAN_RESULT_RES_ID_fkey" FOREIGN KEY ("SCAN_RESULT_RES_ID") REFERENCES "SCAN_RESULT"("RES_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
