-- CreateTable
CREATE TABLE "URL_BATCH" (
    "BAT_ID" SERIAL NOT NULL,
    "BAT_FileName" TEXT NOT NULL,
    "BAT_FileType" TEXT NOT NULL,
    "BAT_TotalURLs" INTEGER NOT NULL,
    "BAT_Status" TEXT NOT NULL,
    "BAT_UploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USER_USR_ID" INTEGER NOT NULL,

    CONSTRAINT "URL_BATCH_pkey" PRIMARY KEY ("BAT_ID")
);

-- CreateTable
CREATE TABLE "URL" (
    "URL_ID" SERIAL NOT NULL,
    "URL_Original" TEXT NOT NULL,
    "URL_Normalized" TEXT NOT NULL,
    "URL_IsDuplicate" BOOLEAN NOT NULL DEFAULT false,
    "URL_CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "URL_BATCH_BAT_ID" INTEGER NOT NULL,
    "DUPLICATE_GROUP_DPG_ID" INTEGER,

    CONSTRAINT "URL_pkey" PRIMARY KEY ("URL_ID")
);

-- AddForeignKey
ALTER TABLE "URL_BATCH" ADD CONSTRAINT "URL_BATCH_USER_USR_ID_fkey" FOREIGN KEY ("USER_USR_ID") REFERENCES "USER"("USR_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "URL" ADD CONSTRAINT "URL_URL_BATCH_BAT_ID_fkey" FOREIGN KEY ("URL_BATCH_BAT_ID") REFERENCES "URL_BATCH"("BAT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
